### ISSUE TITLE
Use virtual displays to record app activity.

### ISSUE THREAD

**Issue by rishi-rranjan** [google/grafika#14]
Hi,
    One of the features in the list to be completed is "Use virtual displays to record app activity.". Can you please let me know if this is even possible today? There is a comment at http://www.bigflake.com/screenrecord/ that "There's no API to allow an application to record itself.". I am trying to record a webview of Cordova App.

Thanks,
Rishi

**Comment by omerjerk** [comment]
Can anyone tell how to exactly use the Presentation API to record the app activity?

I have created a VirtualDisplay which takes a Surface from a SurfaceView.

I understand that I need to use the Presentation API to render on this VirtualDisplay. However I am not really getting it. Any tips?

**Comment by claywilkinson** [comment]
@omerjerk - I added a Screen recording activity sample to show how to use it.
