### ISSUE TITLE
video with multiple views

### ISSUE THREAD

**Issue by dthib** [google/grafika#15]
HI,  

I want to play a video file and duplicate the rendering views eventually with different filters. If I get it right, I can do it using one surfaceview with several quads but it may be difficult to have a flexible layout with other components in between and manage several shaders.

In other words, is there a way to have two surface view pointing to the same video texture or mediaplayer with different shaders for different filter effect.

Thanks for your help, Best, Thibaut

**Comment by rishun-fsi** [comment]
Hi,
Currently, I can not tested it with the new release ver.2.10.0.
Because I have not the test device of BRAVIA 4K 2015 (Android 7.0) around me.
