### ISSUE TITLE
Crash on EGL14.eglReleaseThread()

### ISSUE THREAD

**Issue by lhunath** [google/grafika#18]
EGL14.eglReleaseThread() causes the application to terminate instantly on Android 4.4 devices:

https://github.com/google/grafika/blob/master/src/com/android/grafika/gles/EglCore.java#L191

Simply commenting the call out appears to resolve all issues; I'm unsure whether this is causing any leakage.

**Comment by fadden** [comment]
I've run Grafika on a number of devices and haven't encountered this.  Various CTS tests call eglReleaseThread() with no harmful effects.

Looking through old e-mails, I believe https://android.googlesource.com/platform/cts/+/6d6ce38e075ffe6546041fbafa82140c222a8ad6 went in to ensure eglReleaseThread() was working (I think it failed on a Galaxy Note 3, but I no longer have access to the bug database to see).

If this is crashing on a Nexus device running plain AOSP, you can file a bug on http://b.android.com/.  If it's not, you can post a bug on the manufacturer's support forum.  Be sure to include the device name, exact version of Android, and a clipping from the "adb logcat" output that shows the crash.

In any event, so long as the EGL context and surfaces are being released, any leakage will be very small.
