### ISSUE TITLE
Movie player memory issue

### ISSUE THREAD

**Issue by agustinsivoplas** [google/grafika#21]
Hi all, I am using the movie player to reproduce a list of videos. If I reproduce the videos for a day we have a issue with memory.

I/ActivityManager( 439): Low on memory: 
I/ActivityManager( 439): ntv N 630053 kB: mediaserver (109) native 
I/ActivityManager( 439): ntv N 3631 kB: zygote (107) native 
I/ActivityManager( 439): ntv N 1248 kB: surfaceflinger (106) native 
I/ActivityManager( 439): ntv N 977 kB: drmserver (108) native 
I/ActivityManager( 439): ntv N 531 kB: netd (102) native 

This produces that our applications goes down.

Also I have this trace (like in a loop) in the log:

E/BufferQueue(  106): [SurfaceView] connect: already connected (cur=3, req=3)
E/MediaCodec( 4719): native_window_api_connect returned an error: Invalid argument (-22)
I/OMXClient( 4719): Using client-side OMX mux.
E/BufferQueue(  106): [SurfaceView] connect: already connected (cur=3, req=3)
E/MediaCodec( 4719): native_window_api_connect returned an error: Invalid argument (-22)
I/OMXClient( 4719): Using client-side OMX mux.
E/BufferQueue(  106): [SurfaceView] connect: already connected (cur=3, req=3)
E/MediaCodec( 4719): native_window_api_connect returned an error: Invalid argument (-22)
I/OMXClient( 4719): Using client-side OMX mux.
E/BufferQueue(  106): [SurfaceView] connect: already connected (cur=3, req=3)
E/MediaCodec( 4719): native_window_api_connect returned an error: Invalid argument (-22)
I/OMXClient( 4719): Using client-side OMX mux.
E/BufferQueue(  106): [SurfaceView] connect: already connected (cur=3, req=3)
E/MediaCodec( 4719): native_window_api_connect returned an error: Invalid argument (-22)
I/OMXClient( 4719): Using client-side OMX mux.
E/BufferQueue(  106): [SurfaceView] connect: already connected (cur=3, req=3)

Any idea?

All the best!

**Comment by fadden** [comment]
Something is bloating up mediaserver.  Could be a bug in mediaserver, could be an app is requesting resources and not letting them go.

You can use tools like procrank (on a rooted device) to see the size of things.  If the memory usage of mediaserver drops when you kill your app, then your app is causing the leak.  If your app process is gone but mediaserver is still bloated up, that suggests a mediaserver problem.

Issues with mediaserver should be reported on http://b.android.com/.  If it's an app issue and you need help with it, post a question on http://stackoverflow.com/ with appropriate tags.
