### ISSUE TITLE
How to play video in slow motion for selected intervals

### ISSUE THREAD

**Issue by hubino** [google/grafika#22]
I have run your project(https://github.com/google/grafika) in this project I played a `video` in `slow motion` by changing `Play video(TextureView) activity`'s  `FixedPlaybackRate` value
`SpeedControlCallback callback = new SpeedControlCallback();`
      `callback.setFixedPlaybackRate(1);`
It had played a whole video slowly. what I actually need is have to play video slowly for `selected intervals` not the entire video.is it any possible to set the `regions(intervals)`?.

**Comment by fadden** [comment]
The existing code doesn't provide a way to do this, but you can modify it to define the intervals and have SpeedControlCallback behave appropriately.
