### ISSUE TITLE
How to switch front-back camera in CameraCaptureActivity ?

### ISSUE THREAD

**Issue by jpxiong** [google/grafika#27]
I want to switch the front or back camera in `CameraCaptureActivity`(src/com/android/grafika/CameraCaptureActivity.java), as the following:

```
public boolean switchCamera() {
        releaseCamera();
        mGLView.onPause();
        if (mReqCameraId == Camera.CameraInfo.CAMERA_FACING_BACK) {
            mReqCameraId = Camera.CameraInfo.CAMERA_FACING_FRONT;
        } else {
            mReqCameraId = Camera.CameraInfo.CAMERA_FACING_BACK;
        }
        openCamera(mReqCameraId);

        mGLView.onResume();
        mGLView.queueEvent(new Runnable() {
            @Override
            public void run() {
                mRenderer.setCameraPreviewSize(mCameraPreviewWidth, mCameraPreviewHeight);
            }
        });
        return true;
    }
```

It works, but the FOV has been changed when I back to the camera which first time launched. It seems the frame has been clipped.

So where did i miss when switch the front-back camera?

Thanks.

**Comment by fadden** [comment]
Someone recently discovered that calling `setRecordingHint()` would alter the FOV. Read about it here:

  http://stackoverflow.com/questions/31114191/field-of-camera-preview-is-smaller-if-i-use-the-way-of-preview-in-grifikas-cont

If that doesn't lead you to the solution, you should post a question on http://stackoverflow.com/, using the [android-camera] tag.

**Comment by jpxiong** [comment]
OK. Thanks.
