### ISSUE TITLE
Change the video speed

### ISSUE THREAD

**Issue by zzhopen** [google/grafika#28]
Gratitude can find so good content, 
I want to know, if can Change the video speed,then produce native  video file(different speed).
very thankful.

**Comment by fadden** [comment]
You should ask this on http://stackoverflow.com/, using the [mediacodec] tag.

This recent question may be relevant: http://stackoverflow.com/questions/30972081/how-to-drop-frames-while-recording-with-mediacodec-and-inputsurface
