### ISSUE TITLE
why allways have the bug:Failed to stop the muxer？！

### ISSUE THREAD

**Issue by amazingyyc** [google/grafika#29]
i use the MedaiCodec to recorder the vidoe,when mMuxer.stop(). allways have Failed to stop the muxer？！

**Comment by fadden** [comment]
General questions about the use of MediaCodec and MediaMuxer should be asked on http://stackoverflow.com/ .  Be sure to use the [mediacodec] tag.

**Comment by amazingyyc** [comment]
thanks
