### ISSUE TITLE
MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface failed on Samsung SM-N9100 | Galaxy Note 4

### ISSUE THREAD

**Issue by JuannyWang** [google/grafika#30]
i tried VideoEncoderCore.java to do hw encoder on SM-N9100 | Galaxy Note 4, but i got the following error:
09-10 17:28:39.809: D/VideoEncoderCore(15144): format: {height=480, width=640, bitrate=500000, mime=video/avc, frame-rate=20, i-frame-interval=1, color-format=2130708361}
09-10 17:28:39.809: I/ACodec(15144):  [] Now uninitialized
09-10 17:28:39.809: I/OMXClient(15144): Using client-side OMX mux.
09-10 17:28:39.929: I/ACodec(15144): [OMX.qcom.video.encoder.avc] Now Loaded
09-10 17:28:39.929: E/ACodec(15144): onConfigureComponent mime.c_str() = video/avc
09-10 17:28:39.929: E/ACodec(15144): [OMX.qcom.video.encoder.avc] storeMetaDataInBuffers (output) failed w/ err -2147483648
09-10 17:28:39.929: W/ACodec(15144): do not know color format 0x7fa30c04 = 2141391876
09-10 17:28:39.929: W/ACodec(15144): do not know color format 0x7f000789 = 2130708361
09-10 17:28:39.939: I/ACodec(15144): [OMX.qcom.video.encoder.avc] setupVideoEncoder succeeded
09-10 17:28:39.939: W/ACodec(15144): do not know color format 0x7f000789 = 2130708361
09-10 17:28:39.939: I/ACodec(15144): [OMX.qcom.video.encoder.avc] Now Loaded->Idle
09-10 17:28:39.949: I/ACodec(15144): [OMX.qcom.video.encoder.avc] Now Idle->Executing
09-10 17:28:39.949: I/ACodec(15144): [OMX.qcom.video.encoder.avc] Now Executing
09-10 17:28:39.959: D/EglCore(15144): EGLContext created, client version 3
09-10 17:28:39.979: D/Texture2dProgram(15144): Created program 6 (TEXTURE_EXT)
09-10 17:28:39.979: D/VideoEncoderCore(15144): drainEncoder(false)
09-10 17:28:39.999: D/VideoEncoderCore(15144): drainEncoder(false)
09-10 17:28:40.009: D/VideoEncoderCore(15144): drainEncoder(false)
09-10 17:28:40.029: D/VideoEncoderCore(15144): drainEncoder(false)
09-10 17:28:40.029: D/VideoEncoderCore(15144): encoder output format changed: {height=480, width=640, csd-1=java.nio.ByteArrayBuffer[position=0,limit=8,capacity=8], mime=video/avc, what=1869968451, csd-0=java.nio.ByteArrayBuffer[position=0,limit=17,capacity=17]}

**Comment by fadden** [comment]
Codecs sometimes complain about things that aren't actually failures; see e.g. http://bigflake.com/mediacodec/#q12 .

The last line in the log indicates that acodec has generated the "output format change" notification, which suggests that everything is running fine to that point.

I recommend you post a question on http://stackoverflow.com/, using the [mediacodec] and [grafika] tags, specifying:

 - what it is you're trying to do
 - what is actually happening
 - relevant snippets of code
 - logs near the point of failure

**Comment by JuannyWang** [comment]
i got this link http://stackoverflow.com/questions/31899396/mediacodec-is-giving-a-storemetadatainbuffers-trace-error

it's harmless, please ignore this issue.
