### ISSUE TITLE
recorded video output is so poor

### ISSUE THREAD

**Issue by raytona** [google/grafika#31]
please understand my poor English too..

i try Full-screen record from CameraCaptureActivity. but i got poor quality output.
how can i get better quality output?

**Comment by raytona** [comment]
i just set camera previewsize and encode setting to 1280x720

**Comment by fadden** [comment]
Compare what you see on-screen in the camera preview to the recorded video.

If the preview is poor quality, you need to adjust the way Camera is configured. (Or get a device with a better camera.)

If the preview quality is good, but the recording quality is poor, you may be able to improve it by adjusting the encoding parameters. The basic stuff (like bit rate) is [passed to the CircularEncoder constructor](https://github.com/google/grafika/blob/master/src/com/android/grafika/ContinuousCaptureActivity.java#L378).

It's set for 6Mbps; try bumping that up to 20Mbps and see if the quality improves.  This will triple the amount of memory required.

**Comment by raytona** [comment]
work fine now, thanks!
