### ISSUE TITLE
Loading bitmap texture on encoded video

### ISSUE THREAD

**Issue by raytona** [google/grafika#32]
Hi, thanks for useful awesome example!
i want draw bitmap image on my recorded video, instead of Box in TextureMovieEncoder. (like watermark in video, not camerapreview)

    private void drawBox() {
        int[] textures = new int[1];
        GLES20.glGenTextures(1, textures, 0);
        Bitmap waterMark = BitmapFactory.decodeResource(mContext.getResources(), R.drawable.ic_launcher);
        GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, textures[0]);
        GLUtils.texImage2D(GLES20.GL_TEXTURE_2D, 0, waterMark, 0);
        GLES20.glTexParameterf(GLES20.GL_TEXTURE_2D, GLES20.GL_TEXTURE_MIN_FILTER, GLES20.GL_NEAREST);
        GLES20.glTexParameterf(GLES20.GL_TEXTURE_2D, GLES20.GL_TEXTURE_MAG_FILTER, GLES20.GL_LINEAR);
        waterMark.recycle();
    }

why does this not work?
and how can i make this work?

**Comment by fadden** [comment]
The best place to ask OpenGL ES questions is http://stackoverflow.com/.  Specify the [android] and [opengl-es] tags.

The code you've shown appears to load a Bitmap into a texture, but doesn't issue any draw commands. See the `draw()` function in HardwareScalerActivity.java for an example of drawing textured triangles and rectangles.

**Comment by zhogar** [comment]
It's impossible.

**Comment by zhogar** [comment]
@raytona I can help you. I figured it out. Only help me, popularize the question: [ContinuousCaptureActivity and Camera API 21+](https://github.com/google/grafika/issues/69)

**Comment by anonym24** [comment]
did you find a solution?
