### ISSUE TITLE
About DecodeEditEncodeTest.java

### ISSUE THREAD

**Issue by chenhenry008** [google/grafika#33]
hi Fadden
  I noticed you released some sample code on bigflake.com/mediacodec, one sample is DecodeEditEncodeTest.java
 I am studying this file and have one question: I cannot find the definition of InputSurface and OutputSurface
  Could you also share this part sample code? Thanks a lot.

**Comment by chenhenry008** [comment]
my email is chw_true@126.com, thanks a lot again.

**Comment by antiersolutions** [comment]
have created a sample using grafika code where I am creating the video from camera feeds. In grafika sample there is a method to drawExtra while passing data to muxer which add dots in vidoe. I want to add water mark in place of this at left top corner.

Please suggest.

if (mFileSaveInProgress && showCam) {

         Log.e(TAG, "drawFrame  saving to new video");
          mEncoderSurface.makeCurrent();
          GLES20.glViewport(0, 0,720, 1280);
          mFullFrameBlit.drawFrame(mTextureId, mTmpMatrix);
        drawExtra(mFrameNum, viewWidth, viewHeight);
          mCircEncoder.frameAvailableSoon();
       mEncoderSurface.setPresentationTime(mvideoTexture.getTimestamp());
          mEncoderSurface.swapBuffers();

}
