### ISSUE TITLE
No audio in DoubleDecodeActivity

### ISSUE THREAD

**Issue by HardikSuba** [google/grafika#37]
I am not able to play sound in video. I have used DoubleDecodeActivity to show videos in TextureView.
Is there any solution for it?

I want to play 4 same videos in different angles.

**Comment by fadden** [comment]
The best place to ask this sort of question is on [stackoverflow.com](http://stackoverflow.com/).  Use the tags [android] [grafika] and either [mediacodec] or [android-mediaplayer] depending on how you want to play your videos.

Make sure you describe in detail what it is you're trying to do, e.g. how you want to handle sound coming out of multiple simultaneous video sources.
