### ISSUE TITLE
Nexus 5 crash

### ISSUE THREAD

**Issue by petar19992** [google/grafika#40]
When I try to open TextureFromCameraActivity, my app has stopped working, and this is the main reason:
java.lang.RuntimeException: Fail to connect to camera service
at this line in TextureFromCameraActivity:
 mCamera = Camera.open(i);

**Comment by fadden** [comment]
Sounds like it tried to open the front-facing camera, but failed. This can happen if some other app is already using the camera.

**Comment by petar19992** [comment]
As a matter of fact, there is no other app that uses camera except this one. I restarted the device to make sure that no other app uses it.

**Comment by fadden** [comment]
I don't know what else would be going wrong.  You should post your question to http://stackoverflow.com/, with the [android-camera] tag.

**Comment by testica** [comment]
Do you gave permission to camera access?
In some cases with Android 6.0 you have to do manually. Go to app information -> permission -> allow camera
