### ISSUE TITLE
CameraCaptureActivity bug report

### ISSUE THREAD

**Issue by 275288698** [google/grafika#52]
when i click the "Start recording" button  in CameraCaptureActivity , the crash happen always. 

my phone is HUAWEI P6-U06  , sdk 19

here is the log:
06-12 10:22:37.030: E/AndroidRuntime(6301): FATAL EXCEPTION: TextureMovieEncoder
06-12 10:22:37.030: E/AndroidRuntime(6301): Process: com.android.grafika, PID: 6301
06-12 10:22:37.030: E/AndroidRuntime(6301): java.lang.RuntimeException: eglCreateContext: EGL error: 0x3009
06-12 10:22:37.030: E/AndroidRuntime(6301): 	at com.android.grafika.gles.EglCore.checkEglError(EglCore.java:370)
06-12 10:22:37.030: E/AndroidRuntime(6301): 	at com.android.grafika.gles.EglCore.<init>(EglCore.java:126)
06-12 10:22:37.030: E/AndroidRuntime(6301): 	at com.android.grafika.TextureMovieEncoder.prepareEncoder(TextureMovieEncoder.java:385)
06-12 10:22:37.030: E/AndroidRuntime(6301): 	at com.android.grafika.TextureMovieEncoder.handleStartRecording(TextureMovieEncoder.java:312)
06-12 10:22:37.030: E/AndroidRuntime(6301): 	at com.android.grafika.TextureMovieEncoder.access$0(TextureMovieEncoder.java:309)
06-12 10:22:37.030: E/AndroidRuntime(6301): 	at com.android.grafika.TextureMovieEncoder$EncoderHandler.handleMessage(TextureMovieEncoder.java:281)
06-12 10:22:37.030: E/AndroidRuntime(6301): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-12 10:22:37.030: E/AndroidRuntime(6301): 	at android.os.Looper.loop(Looper.java:136)
06-12 10:22:37.030: E/AndroidRuntime(6301): 	at com.android.grafika.TextureMovieEncoder.run(TextureMovieEncoder.java:248)
06-12 10:22:37.030: E/AndroidRuntime(6301): 	at java.lang.Thread.run(Thread.java:841)
06-12 10:22:37.050: E/BufferQueue(6301): [unnamed-6301-0] cancelBuffer: slot 1 is not owned by the client (state=3)
06-12 10:22:37.050: E/BufferQueue(6301): [unnamed-6301-0] cancelBuffer: slot 3 is not owned by the client (state=0)
06-12 10:22:37.050: E/BufferQueue(6301): [unnamed-6301-0] cancelBuffer: slot 0 is not owned by the client (state=0)
06-12 10:22:37.050: E/BufferQueue(6301): [unnamed-6301-0] cancelBuffer: slot 1 is not owned by the client (state=3)
06-12 10:22:37.050: E/BufferQueue(6301): [unnamed-6301-0] cancelBuffer: slot 2 is not owned by the client (state=0)
06-12 10:22:37.050: E/BufferQueue(6301): [unnamed-6301-0] cancelBuffer: slot 3 is not owned by the client (state=0)

==================================================================
is this phone doesn't support the opengles?  is there any way to avoid this?
appreciate ur answer.

**Comment by 275288698** [comment]
i hava search the error code 0x3009 mean:
EGL_BAD_MATCH is generated if the current rendering API is EGL_NONE (this can only arise in an EGL implementation which does not support OpenGL ES, prior to the first call to eglBindAPI).

EGL_BAD_MATCH is generated if the server context state for share_context exists in an address space which cannot be shared with the newly created context, if share_context was created on a different display than the one referenced by config, or if the contexts are otherwise incompatible.

**Comment by fadden** [comment]
If you're running the stock version of Grafika then I would guess it's a problem with that specific device.  Sounds like the handling of shared EGL contexts is broken.

The HUAWEI P6-U06 [appears to use](http://www.gsmarena.com/huawei_ascend_p6-5467.php) a Vivante GPU.  I've seen some strange things from them in the past, e.g. [this post](http://stackoverflow.com/questions/26359917/opengl-es-2-on-vivante-gpu-android-depth-buffer-doesnt-work) and [this post](http://stackoverflow.com/questions/36654216/video-lag-and-fps-drop-on-android-lollipop-on-touching-screen/).

You can work around the problem by not using shared contexts, something I recommend anyway (see #36).

**Comment by 275288698** [comment]
thanks,fadden, and i will try it

**Comment by yaoliu1025** [comment]
Hello! I am facing the exact same issue on the same phone. I believe it is indeed a shared context problem. Because if I change the sharedContext here https://github.com/google/grafika/blob/master/src/com/android/grafika/TextureMovieEncoder.java#L385 to EGL14.eglGetCurrentContext(), then the camera opens (however the recording seems to be broken still, because there is no image, just sound). I don't really know how to work around the problem by not using shared context correctly? Could anyone please provide any help? Thanks a lot!
