### ISSUE TITLE
Drawing text

### ISSUE THREAD

**Issue by CreaRo** [google/grafika#74]
@fadden I'd like to display a logo, timestamp and fps on the video. 
I've been able to successfully draw a Bitmap using `GLUtils.texImage2D()` on the video, drawing two rects (One `Sprite2D` for the logo and one `FullFrameRect` for the video) on one `WindowSurface`. How should I draw text? Reading on the Internet I see it isn't as straight forward as I thought it would be.

Edit : An easy option seems to lock the `WindowSurface'`s canvas and use the `Canvas` API to draw, like [here](https://stackoverflow.com/questions/9914797/how-to-set-a-drawtext-in-a-surfaceview). Do you see any drawback to this?

**Comment by fadden** [comment]
Rendering text with OpenGL ES is a common problem (e.g. [this](https://stackoverflow.com/questions/23735464/how-to-embed-text-while-recording-video-in-android/23740995#23740995)).  You can find a few solutions around.

Last I checked, Android's software-rendering API didn't know how to let go of a Surface.  So you can either render with GLES or with software on a given Surface, but not both.

For your situation, you can probably just render text to a Bitmap, then render it like you do the logo.  Depending on the precision of your timestamp and FPS meter you may not need to render them every frame.

**Comment by CreaRo** [comment]
Thanks for the quick response! That's exactly what I ended up doing right after I posted the question. I've decided to update the bitmap once every second for now. Thanks a lot!

**Comment by CreaRo** [comment]
Commenting for anyone trying this in the future - I was stuck at quite an interesting problem. I was unable to draw a transparent texture on top of the video texture. I created a transparent text bitmap using the following :

    public Bitmap fromText(String text, int textSize, @ColorInt int textColor) {
        Paint paint = new Paint();
        paint.setTextSize(textSize);
        paint.setColor(Color.WHITE);
        float baseline = -paint.ascent(); // ascent() is negative
        int width = (int) (paint.measureText(text) + 1.0f);
        int height = (int) (baseline + paint.descent() + 1.0f);
        Bitmap bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);
        bitmap.setHasAlpha(true);
        Canvas canvas = new Canvas(bitmap);
        // canvas.drawColor(Color.argb(0, 255, 255, 255));
        canvas.drawColor(Color.TRANSPARENT, PorterDuff.Mode.CLEAR);
        canvas.drawText(text, 0, baseline, paint);
        return bitmap;
    }

Specifically, this is the [image link]( https://ibb.co/fPVSdk) depicting the black box. When I save the above Bitmap as a PNG file, it's transparent with only white text. I've created a `Sprite3D` class similar to Sprite2D, but has depth too. At first I thought it was because both the sprites were at the same depth that the bitmap was not drawn with a transparent background. However, bringing the bitmap in front of the video did not remove the black background either. 

Next, I thought it was to do with texture not being able to draw on another texture. Figured it must have something to do with the way I was creating the texture, specifically the texImage2D call. 

    public void setBitmap(Bitmap bitmap, int textureId) {
        GLES20.glActiveTexture(GLES20.GL_TEXTURE0);
        GLES20.glBindTexture(mTextureTarget, textureId);
        GLES20.glEnable(GLES20.GL_BLEND); // this, and the next line
        GLES20.glBlendFunc(GLES20.GL_ONE, GLES20.GL_ONE_MINUS_SRC_ALPHA); // and this were key! I'm still not completely sure as to what this is doing, but it works!
        GLUtils.texImage2D(GLES20.GL_TEXTURE_2D, 0, GLES20.GL_RGBA, bitmap, 0);
    }

And it finally worked! (View here)[https://ibb.co/ekahB5]

Hope this helps someone.

**Comment by borzadaran** [comment]
Great!

**Comment by kishorejethava** [comment]
@crearo Do you have any sample code?
I'm confused about where should I start.
I want to draw Emoji, Text, and Paint.
Waiting for your reply!

**Comment by devillee** [comment]
@crearo I want to draw timestamp for a recorded video , do you have some example like https://ibb.co/ekahB5 , this is what I need.
I am try to draw timestamp with GLText : http://fractiousg.blogspot.com/2012/04/rendering-text-in-opengl-on-android.html but not work well.

**Comment by crearo** [comment]
Yes, the code example above is how I'm drawing the timestamp bitmap to video.

**Comment by anonym24** [comment]
@crearo and where do you call method `setBitmap(Bitmap bitmap, int textureId)`?

for example where should I call it in **Show + capture camera activity** (CameraCaptureActivity.java) https://github.com/google/grafika/blob/master/app/src/main/java/com/android/grafika/CameraCaptureActivity.java

**Comment by anonym24** [comment]
do you call `setBitmap `method somewhere in Texture2dProgram.java draw method? https://github.com/google/grafika/blob/master/app/src/main/java/com/android/grafika/gles/Texture2dProgram.java#L287

**Comment by anonym24** [comment]
I also replaced `mTextureTarget `to` textureId` but it still didn't help

`setBitmap(fromText("test text", 25), textureId);`

**Comment by anonym24** [comment]
@crearo 

and what do you mean by


> there is a bug in Grafika where they've used GLES11Ext.GL_TEXTURE_EXTERNAL_OES in the createTextureObject() in Texture2dProgram.java, instead of mTargetTexture

replace

 ```
   public int createTextureObject() {
        GLES20.glGenTextures(1, textures, 0);
        GlUtil.checkGlError("glGenTextures");

        int texId = textures[0];
        GLES20.glBindTexture(mTextureTarget, texId);
        GlUtil.checkGlError("glBindTexture " + texId);

        GLES20.glTexParameterf(GLES11Ext.GL_TEXTURE_EXTERNAL_OES, GLES20.GL_TEXTURE_MIN_FILTER,
                GLES20.GL_NEAREST);
        GLES20.glTexParameterf(GLES11Ext.GL_TEXTURE_EXTERNAL_OES, GLES20.GL_TEXTURE_MAG_FILTER,
                GLES20.GL_LINEAR);
        GLES20.glTexParameteri(GLES11Ext.GL_TEXTURE_EXTERNAL_OES, GLES20.GL_TEXTURE_WRAP_S,
                GLES20.GL_CLAMP_TO_EDGE);
        GLES20.glTexParameteri(GLES11Ext.GL_TEXTURE_EXTERNAL_OES, GLES20.GL_TEXTURE_WRAP_T,
                GLES20.GL_CLAMP_TO_EDGE);
        GlUtil.checkGlError("glTexParameter");
        return texId;
    }
```

to

  ```
  public int createTextureObject() {
        GLES20.glGenTextures(1, textures, 0);
        GlUtil.checkGlError("glGenTextures");

        int texId = textures[0];
        GLES20.glBindTexture(mTextureTarget, texId);
        GlUtil.checkGlError("glBindTexture " + texId);

        GLES20.glTexParameterf(mTextureTarget, GLES20.GL_TEXTURE_MIN_FILTER,
                GLES20.GL_NEAREST);
        GLES20.glTexParameterf(mTextureTarget, GLES20.GL_TEXTURE_MAG_FILTER,
                GLES20.GL_LINEAR);
        GLES20.glTexParameteri(mTextureTarget, GLES20.GL_TEXTURE_WRAP_S,
                GLES20.GL_CLAMP_TO_EDGE);
        GLES20.glTexParameteri(mTextureTarget, GLES20.GL_TEXTURE_WRAP_T,
                GLES20.GL_CLAMP_TO_EDGE);
        GlUtil.checkGlError("glTexParameter");
        return texId;
    }
```
?

**Comment by anonym24** [comment]
I also tried to generate new id:

```
        int[] textures = new int[1];
        GLES20.glGenTextures(1, textures, 0);
        setBitmap(fromText("test text", 25), textures[0]);
```

but still nothing in recorder video

**Comment by crearo** [comment]
I've given a full example at http://github.com/crearo/grafika in the `TextOnPreviewActivity.java`.

**Comment by anonym24** [comment]
@crearo awesome, thanks!

**Comment by zhangsl** [comment]
> @crearo your example contains only preview without video recording (encoding)
> 
> I opened your cloned, edited Grafika project and I tried to move some code from `TextOnPreviewActivity.java` to `TextureMovieEncoder.java` (CameraCaptureActivity uses this class for video recording)
> 
> It draws frame textures with my bitmap on encoding video ok, but background of bitmap isn't transparent, though it is transparent for preview of `TextOnPreviewActivity`
> 
> Do you have example with video recording or can you help please with my code example?
> 
> ![screenshot_2018-07-22-12-19-14-068_com android grafika](https://user-images.githubusercontent.com/8851301/43044196-8993d20c-8daa-11e8-9da0-d56c7f93b211.png)
> 
> Code:
> 
> ```
> public class TextureMovieEncoder implements Runnable {
>     private static final String TAG = MainActivity.TAG;
>     private static final boolean VERBOSE = false;
> 
>     private static final int MSG_START_RECORDING = 0;
>     private static final int MSG_STOP_RECORDING = 1;
>     private static final int MSG_FRAME_AVAILABLE = 2;
>     private static final int MSG_SET_TEXTURE_ID = 3;
>     private static final int MSG_UPDATE_SHARED_CONTEXT = 4;
>     private static final int MSG_QUIT = 5;
> 
>     // ----- accessed exclusively by encoder thread -----
>     private WindowSurface mInputWindowSurface;
>     private EglCore mEglCore;
>     private FullFrameRect mFullScreen;
> 
>     private Sprite3d mVideoSprite;
>     private Texture2dProgram mVideoProgram;
>     private float[] mDisplayProjectionMatrix = new float[16];
> 
>     private int mTextureId;
>     private int mFrameNum;
>     private VideoEncoderCore mVideoEncoder;
> 
>     // ----- accessed by multiple threads -----
>     private volatile EncoderHandler mHandler;
> 
>     private Object mReadyFence = new Object();      // guards ready/running
>     private boolean mReady;
>     private boolean mRunning;
> 
>     private Texture2dProgram mLogoProgram;
>     private Sprite3d mLogoRect;
> 
>     public void setActivity(Activity activity) {
>         mActivity = activity;
>     }
> 
>     private Activity mActivity;
> 
> 
>     /**
>      * Encoder configuration.
>      * <p>
>      * Object is immutable, which means we can safely pass it between threads without
>      * explicit synchronization (and don't need to worry about it getting tweaked out from
>      * under us).
>      * <p>
>      * TODO: make frame rate and iframe interval configurable?  Maybe use builder pattern
>      *       with reasonable defaults for those and bit rate.
>      */
>     public static class EncoderConfig {
>         final File mOutputFile;
>         final int mWidth;
>         final int mHeight;
>         final int mBitRate;
>         final EGLContext mEglContext;
> 
>         public EncoderConfig(File outputFile, int width, int height, int bitRate,
>                 EGLContext sharedEglContext) {
>             mOutputFile = outputFile;
>             mWidth = width;
>             mHeight = height;
>             mBitRate = bitRate;
>             mEglContext = sharedEglContext;
>         }
> 
>         @Override
>         public String toString() {
>             return "EncoderConfig: " + mWidth + "x" + mHeight + " @" + mBitRate +
>                     " to '" + mOutputFile.toString() + "' ctxt=" + mEglContext;
>         }
>     }
> 
>     /**
>      * Tells the video recorder to start recording.  (Call from non-encoder thread.)
>      * <p>
>      * Creates a new thread, which will create an encoder using the provided configuration.
>      * <p>
>      * Returns after the recorder thread has started and is ready to accept Messages.  The
>      * encoder may not yet be fully configured.
>      */
>     public void startRecording(EncoderConfig config) {
>         Log.d(TAG, "Encoder: startRecording()");
>         synchronized (mReadyFence) {
>             if (mRunning) {
>                 Log.w(TAG, "Encoder thread already running");
>                 return;
>             }
>             mRunning = true;
>             new Thread(this, "TextureMovieEncoder").start();
>             while (!mReady) {
>                 try {
>                     mReadyFence.wait();
>                 } catch (InterruptedException ie) {
>                     // ignore
>                 }
>             }
>         }
> 
>         setLogoSprite();
>         mHandler.sendMessage(mHandler.obtainMessage(MSG_START_RECORDING, config));
>     }
> 
>     /**
>      * Tells the video recorder to stop recording.  (Call from non-encoder thread.)
>      * <p>
>      * Returns immediately; the encoder/muxer may not yet be finished creating the movie.
>      * <p>
>      * TODO: have the encoder thread invoke a callback on the UI thread just before it shuts down
>      * so we can provide reasonable status UI (and let the caller know that movie encoding
>      * has completed).
>      */
>     public void stopRecording() {
>         mHandler.sendMessage(mHandler.obtainMessage(MSG_STOP_RECORDING));
>         mHandler.sendMessage(mHandler.obtainMessage(MSG_QUIT));
>         // We don't know when these will actually finish (or even start).  We don't want to
>         // delay the UI thread though, so we return immediately.
>     }
> 
>     /**
>      * Returns true if recording has been started.
>      */
>     public boolean isRecording() {
>         synchronized (mReadyFence) {
>             return mRunning;
>         }
>     }
> 
>     /**
>      * Tells the video recorder to refresh its EGL surface.  (Call from non-encoder thread.)
>      */
>     public void updateSharedContext(EGLContext sharedContext) {
>         mHandler.sendMessage(mHandler.obtainMessage(MSG_UPDATE_SHARED_CONTEXT, sharedContext));
>     }
> 
>     /**
>      * Tells the video recorder that a new frame is available.  (Call from non-encoder thread.)
>      * <p>
>      * This function sends a message and returns immediately.  This isn't sufficient -- we
>      * don't want the caller to latch a new frame until we're done with this one -- but we
>      * can get away with it so long as the input frame rate is reasonable and the encoder
>      * thread doesn't stall.
>      * <p>
>      * TODO: either block here until the texture has been rendered onto the encoder surface,
>      * or have a separate "block if still busy" method that the caller can execute immediately
>      * before it calls updateTexImage().  The latter is preferred because we don't want to
>      * stall the caller while this thread does work.
>      */
>     public void frameAvailable(SurfaceTexture st) {
>         synchronized (mReadyFence) {
>             if (!mReady) {
>                 return;
>             }
>         }
> 
>         float[] transform = new float[16];      // TODO - avoid alloc every frame
>         st.getTransformMatrix(transform);
>         long timestamp = st.getTimestamp();
>         if (timestamp == 0) {
>             // Seeing this after device is toggled off/on with power button.  The
>             // first frame back has a zero timestamp.
>             //
>             // MPEG4Writer thinks this is cause to abort() in native code, so it's very
>             // important that we just ignore the frame.
>             Log.w(TAG, "HEY: got SurfaceTexture with timestamp of zero");
>             return;
>         }
> 
>         mHandler.sendMessage(mHandler.obtainMessage(MSG_FRAME_AVAILABLE,
>                 (int) (timestamp >> 32), (int) timestamp, transform));
>     }
> 
>     /**
>      * Tells the video recorder what texture name to use.  This is the external texture that
>      * we're receiving camera previews in.  (Call from non-encoder thread.)
>      * <p>
>      * TODO: do something less clumsy
>      */
>     public void setTextureId(int id) {
>         synchronized (mReadyFence) {
>             if (!mReady) {
>                 return;
>             }
>         }
>         mHandler.sendMessage(mHandler.obtainMessage(MSG_SET_TEXTURE_ID, id, 0, null));
>     }
> 
>     /**
>      * Encoder thread entry point.  Establishes Looper/Handler and waits for messages.
>      * <p>
>      * @see java.lang.Thread#run()
>      */
>     @Override
>     public void run() {
>         // Establish a Looper for this thread, and define a Handler for it.
>         Looper.prepare();
>         synchronized (mReadyFence) {
>             mHandler = new EncoderHandler(this);
>             mReady = true;
>             mReadyFence.notify();
>         }
>         Looper.loop();
> 
>         Log.d(TAG, "Encoder thread exiting");
>         synchronized (mReadyFence) {
>             mReady = mRunning = false;
>             mHandler = null;
>         }
>     }
> 
>     public Bitmap fromText(String text, int textSize) {
>         Paint paint = new Paint();
>         paint.setTextSize(textSize);
>         paint.setColor(Color.WHITE);
>         paint.setAntiAlias(true);
>         float baseline = -paint.ascent(); // ascent() is negative
>         int width = (int) (paint.measureText(text) + 1.0f);
>         int height = (int) (baseline + paint.descent() + 1.0f);
>         Bitmap bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);
>         bitmap.setHasAlpha(true);
>         Canvas canvas = new Canvas(bitmap);
>         // canvas.drawColor(Color.argb(0, 255, 255, 255));
>         canvas.drawColor(Color.TRANSPARENT, PorterDuff.Mode.CLEAR);
>         canvas.drawText(text, 0, baseline, paint);
>         return bitmap;
>     }
> 
>     private void setLogoSprite() {
>         Bitmap logoBitmap =  fromText("TEST", 25);// BitmapFactory.decodeResource(getResources(), R.drawable.ic_logo_128);
>         int logoHeight = logoBitmap.getHeight();
>         int logoWidth = logoBitmap.getWidth();
> 
>         Log.d(TAG, "Video sprite : " + logoWidth + " " + logoHeight);
> 
>         mLogoProgram = new Texture2dProgram(Texture2dProgram.ProgramType.TEXTURE_2D);
>         mLogoRect = new Sprite3d(new Drawable2d(logoWidth, logoHeight));
>         int logoTextureId = mLogoProgram.createTextureObject();
>         mLogoRect.setTextureId(logoTextureId);
>         mLogoProgram.setBitmap(logoBitmap, logoTextureId);
>         logoBitmap.recycle();
>         mLogoRect.transform(new Sprite3d.Transformer()
>                 .translate(0, 0, 0)
>                 .scale(1.0f, 1.0f, 1.0f)
>                 .build());
>     }
> 
>     /**
>      * Handles encoder state change requests.  The handler is created on the encoder thread.
>      */
>     private static class EncoderHandler extends Handler {
>         private WeakReference<TextureMovieEncoder> mWeakEncoder;
> 
>         public EncoderHandler(TextureMovieEncoder encoder) {
>             mWeakEncoder = new WeakReference<TextureMovieEncoder>(encoder);
>         }
> 
>         @Override  // runs on encoder thread
>         public void handleMessage(Message inputMessage) {
>             int what = inputMessage.what;
>             Object obj = inputMessage.obj;
> 
>             TextureMovieEncoder encoder = mWeakEncoder.get();
>             if (encoder == null) {
>                 Log.w(TAG, "EncoderHandler.handleMessage: encoder is null");
>                 return;
>             }
> 
>             switch (what) {
>                 case MSG_START_RECORDING:
>                     encoder.handleStartRecording((EncoderConfig) obj);
>                     break;
>                 case MSG_STOP_RECORDING:
>                     encoder.handleStopRecording();
>                     break;
>                 case MSG_FRAME_AVAILABLE:
>                     long timestamp = (((long) inputMessage.arg1) << 32) |
>                             (((long) inputMessage.arg2) & 0xffffffffL);
>                     encoder.handleFrameAvailable((float[]) obj, timestamp);
>                     break;
>                 case MSG_SET_TEXTURE_ID:
>                     encoder.handleSetTexture(inputMessage.arg1);
>                     break;
>                 case MSG_UPDATE_SHARED_CONTEXT:
>                     encoder.handleUpdateSharedContext((EGLContext) inputMessage.obj);
>                     break;
>                 case MSG_QUIT:
>                     Looper.myLooper().quit();
>                     break;
>                 default:
>                     throw new RuntimeException("Unhandled msg what=" + what);
>             }
>         }
>     }
> 
>     /**
>      * Starts recording.
>      */
>     private void handleStartRecording(EncoderConfig config) {
>         Log.d(TAG, "handleStartRecording " + config);
>         mFrameNum = 0;
>         prepareEncoder(config.mEglContext, config.mWidth, config.mHeight, config.mBitRate,
>                 config.mOutputFile);
>     }
> 
>     /**
>      * Handles notification of an available frame.
>      * <p>
>      * The texture is rendered onto the encoder's input surface, along with a moving
>      * box (just because we can).
>      * <p>
>      * @param transform The texture transform, from SurfaceTexture.
>      * @param timestampNanos The frame's timestamp, from SurfaceTexture.
>      */
>     private void handleFrameAvailable(float[] transform, long timestampNanos) {
>         if (VERBOSE) Log.d(TAG, "handleFrameAvailable tr=" + transform);
>         mVideoEncoder.drainEncoder(false);
> 
>         GLES20.glViewport(0, 0, mInputWindowSurface.getWidth(), mInputWindowSurface.getHeight());
> 
>         mVideoProgram.clearScreen();
>         //mFullScreen.drawFrame(mTextureId, transform);
>        //
>         mVideoSprite.draw(mVideoProgram, mDisplayProjectionMatrix, transform);
> 
>         mLogoRect.draw(mLogoProgram, mDisplayProjectionMatrix, GlUtil.IDENTITY_MATRIX);
>         //drawBox(mFrameNum++);
> 
>         mInputWindowSurface.setPresentationTime(timestampNanos);
>         mInputWindowSurface.swapBuffers();
>     }
> 
>     /**
>      * Handles a request to stop encoding.
>      */
>     private void handleStopRecording() {
>         Log.d(TAG, "handleStopRecording");
>         mVideoEncoder.drainEncoder(true);
>         releaseEncoder();
>     }
> 
>     /**
>      * Sets the texture name that SurfaceTexture will use when frames are received.
>      */
>     private void handleSetTexture(int id) {
>         //Log.d(TAG, "handleSetTexture " + id);
>         mTextureId = id;
>         mVideoSprite.setTextureId(mTextureId);
>     }
> 
>     /**
>      * Tears down the EGL surface and context we've been using to feed the MediaCodec input
>      * surface, and replaces it with a new one that shares with the new context.
>      * <p>
>      * This is useful if the old context we were sharing with went away (maybe a GLSurfaceView
>      * that got torn down) and we need to hook up with the new one.
>      */
>     private void handleUpdateSharedContext(EGLContext newSharedContext) {
>         Log.d(TAG, "handleUpdatedSharedContext " + newSharedContext);
> 
>         // Release the EGLSurface and EGLContext.
>         mInputWindowSurface.releaseEglSurface();
>         mFullScreen.release(false);
>         mEglCore.release();
> 
>         // Create a new EGLContext and recreate the window surface.
>         mEglCore = new EglCore(newSharedContext, EglCore.FLAG_RECORDABLE);
>         mInputWindowSurface.recreate(mEglCore);
>         mInputWindowSurface.makeCurrent();
> 
>         // Create new programs and such for the new context.
>         mFullScreen = new FullFrameRect(
>                 new Texture2dProgram(Texture2dProgram.ProgramType.TEXTURE_EXT));
>     }
> 
>     private void prepareEncoder(EGLContext sharedContext, int width, int height, int bitRate,
>             File outputFile) {
>         try {
>             mVideoEncoder = new VideoEncoderCore(width, height, bitRate, outputFile);
>         } catch (IOException ioe) {
>             throw new RuntimeException(ioe);
>         }
>         mEglCore = new EglCore(sharedContext, EglCore.FLAG_RECORDABLE);
>         mInputWindowSurface = new WindowSurface(mEglCore, mVideoEncoder.getInputSurface(), true);
>         mInputWindowSurface.makeCurrent();
> 
>         float screenAspect = ((float) mInputWindowSurface.getWidth()) / mInputWindowSurface.getHeight();
> 
>         float near = -1.0f, far = 1.0f,
>                 right = width / 2,
>                 top = right / screenAspect;
> 
>         Matrix.orthoM(mDisplayProjectionMatrix, 0,
>                 -right, right,
>                 -top, top,
>                 near, far);
> 
>         mVideoSprite = new Sprite3d(new Drawable2d(width, height));
>         mVideoProgram = new Texture2dProgram(Texture2dProgram.ProgramType.TEXTURE_EXT);
>         int videoTextureId = mVideoProgram.createTextureObject();
>         mVideoSprite.setTextureId(mTextureId);
> 
>         mVideoSprite.transform(new Sprite3d.Transformer()
>                 .reset()
>                 .translate(0, 0, 0)
>                 .rotateAroundZ(0)
>                 .scale(1, 1, 1)
>                 .build());
> 
>         mFullScreen = new FullFrameRect(
>                 new Texture2dProgram(Texture2dProgram.ProgramType.TEXTURE_EXT));
>     }
> 
>     private void releaseEncoder() {
>         mVideoEncoder.release();
>         if (mInputWindowSurface != null) {
>             mInputWindowSurface.release();
>             mInputWindowSurface = null;
>         }
>         if (mFullScreen != null) {
>             mFullScreen.release(false);
>             mFullScreen = null;
>         }
>         if (mVideoSprite != null) {
>             mVideoSprite = null;
>         }
>         if (mEglCore != null) {
>             mEglCore.release();
>             mEglCore = null;
>         }
>     }
> 
> }
> ```

OpenGL disable alpha blend by default, you should enable it: 

GLES20.glEnable(GLES20.GL_BLEND);
GLES20.glBlendFunc(GLES20.GL_ONE, GLES20.GL_ONE_MINUS_SRC_ALPHA);

**Comment by crearo** [comment]
I did this a long time ago, so I don't quite remember. But, it depends on how you're rendering the text. When it's placed in a sprite2d, you can perform any affine function and rotate/move/scale it. Also, if you want to make it easy, you can also rotate the bitmap.

**Comment by SaravanarajaGITHUB** [comment]
`  mSpriteLogoRect.transform(new Sprite3d.Transformer()
                .rotateAroundX(180) //this line made the trick
                .translate(0, 0, 0)
                .scale(1.0f, 1.0f, 1.0f)
                .build());`

**Comment by SaravanarajaGITHUB** [comment]
> I did this a long time ago, so I don't quite remember. But, it depends on how you're rendering the text. When it's placed in a sprite2d, you can perform any affine function and rotate/move/scale it. Also, if you want to make it easy, you can also rotate the bitmap.

  `mSpriteLogoRect.transform(new Sprite3d.Transformer()
                .rotateAroundX(180) 
                .translate(0, 0, 0)
                .scale(1.0f, 1.0f, 1.0f)
                .build());`

 .rotateAroundX(180) //this line made the trick

**Comment by bkg866** [comment]
Hello Greetings!

- I have a question from GLSurfaceView.Renderer. it is possible to surface tap puts points or multiple points draw line without dragging finger.?

- Right now i have surface tapped and finger pressed and moved device draw line.

Waiting for your reply.

Thanks
