### ISSUE TITLE
ContinuousCaptureActivity -- Incorrect buffer time

### ISSUE THREAD

**Issue by pro-softs** [google/grafika#86]
Hi,
I am setting the buffer time for the circular buffer in the ContinuousCaptureActivity to 20 sec but the timer keeps on increasing much more than 20 sec and the captured video is of higher length too. Can anyone please explains this behavior as I think it is happening to higher buffer values like in 40 sec buffer time, the timer goes up to 80 sec (just double).

Thanks.

**Comment by pro-softs** [comment]
Any Help??

**Comment by zhogar** [comment]
Hi,
this is related to the codec used. The fact is that you have a fixed buffer size, but at low video quality, the mpeg codec squeezes the data much more.

**Comment by zhogar** [comment]
Try to shoot the video in sunny weather, make sure the video takes 20 seconds. This will be the high quality you set when creating the object.

**Comment by zhogar** [comment]
See the code:
[public CircularEncoderBuffer(int bitRate, int frameRate, int desiredSpanSec) {](https://github.com/google/grafika/blob/c747398a8f0d5c8ec7be2c66522a80b43dfc9a1e/app/src/main/java/com/android/grafika/CircularEncoderBuffer.java#L66)

and comment:
[adjust bit rate based on frame rate?](https://github.com/google/grafika/blob/c747398a8f0d5c8ec7be2c66522a80b43dfc9a1e/app/src/main/java/com/android/grafika/ContinuousCaptureActivity.java#L409)
